### ISSUE TITLE
How to use the IndexedDbAdapter?

### ISSUE THREAD

**Issue by knoepsche** [mydea/ember-indexeddb#3]
I have a model 'einstellungen' with its own IndexedDbAdapter:

`import IndexedDbAdapter from 'ember-indexeddb/adapters/indexed-db;`
`export default IndexedDbAdapter.extend({});`

I want to do something like this:
`var einst = this.get('store').createRecord('einstellungen',{id: 'myid'});`
`einst.save();`

The createRecord command works. But when saving I get a TypeError:
_Cannot read property 'put' of undefined_
it's in the indexed-db.js where the save-function is defined:
`return db[type].put(data).then(resolve, reject)`

Using the IndexedDb service saving works like this:
`this.get('indexedDb').save('einstellungens', 'myId', einst)`

How should I use the IndexedDbAdapter?

**Comment by mydea** [comment]
I'm guessing it has something to do with the pluralization and the model name.
When defining your tables in the indexed-db-configuration service, the adapter assumes you use dasherized, singular model names.

From your comment, I assume you configured the table for 'einstellungens' instead of 'einstellungen'? 

See: https://mydea.github.io/ember-indexeddb/docs/classes/IndexedDbConfiguration.html#property_currentVersion

**Comment by mydea** [comment]
I've added some more information on this (see https://mydea.github.io/ember-indexeddb/docs/modules/Ember%20Data.html), and also changed the bahvior so that it will auto-add a basic `indexed-db-configuration.js` service with basic instructions on installation - I hope this helps.
